# Modify this
SRC = Insert_into_Attractions

# Default 'recipe'
all:
	gcc $(SRC).c -o $(SRC)

# Cleaning  (be wary of this in directories with lots of executables...)
clean:
	rm *.o
	rm *.hex
