# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('streetNum', models.IntegerField()),
                ('StreetName', models.CharField(max_length=30)),
                ('suburb', models.CharField(max_length=30)),
                ('areaCode', models.IntegerField()),
                ('website', models.URLField(max_length=30)),
                ('attractionType', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='user',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('email', models.EmailField(max_length=30)),
        #         ('firstNme', models.CharField(max_length=30)),
        #         ('lastName', models.CharField(max_length=30)),
        #         ('userType', models.CharField(max_length=30)),
        #         ('password', models.CharField(max_length=30)),
        #     ],
        # ),
    ]
