# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('streetNum', models.IntegerField()),
                ('StreetName', models.CharField(max_length=30)),
                ('suburb', models.CharField(max_length=30)),
                ('areaCode', models.IntegerField()),
                ('attractionType', models.CharField(max_length=30)),
            ],
        ),
    ]
