# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='updated',
        ),
        migrations.AddField(
            model_name='signup',
            name='account_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
