# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createuser', '0002_auto_20171023_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
